#include "certificateinfo.h"
#include "ui_certificateinfo.h"

CertificateInfo::CertificateInfo(QSslCertificate certificate, QWidget *parent) :
    QDialog(parent),
    ui(new Ui::CertificateInfo)
{
    ui->setupUi(this);

    this->certificate = certificate;

    //Fill Subject Info fields
    ui->subjectCommonName->setText(certificate.subjectInfo(QSslCertificate::CommonName).join(", "));
    ui->subjectOrganisation->setText(certificate.subjectInfo(QSslCertificate::Organization).join(", "));
    ui->subjectOrganisationalUnit->setText(certificate.subjectInfo(QSslCertificate::OrganizationalUnitName).join(", "));

    ui->issuerCommonName->setText(certificate.issuerInfo(QSslCertificate::CommonName).join(", "));
    ui->issuerOrganisation->setText(certificate.issuerInfo(QSslCertificate::Organization).join(", "));
    ui->issuerOrganisationalUnit->setText(certificate.issuerInfo(QSslCertificate::OrganizationalUnitName).join(", "));

    ui->expiryStart->setText(certificate.effectiveDate().toString("dddd, d MMMM yyyy, hh:mm:ss"));
    ui->expiryEnd->setText(certificate.expiryDate().toString("dddd, d MMMM yyyy, hh:mm:ss"));

    ui->sha256->setText(certificate.digest(QCryptographicHash::Sha256).toHex().toUpper());
    ui->sha1->setText(certificate.digest(QCryptographicHash::Sha1).toHex().toUpper());
}

CertificateInfo::CertificateInfo(QString type, QWidget *parent) :
    QDialog(parent),
    ui(new Ui::CertificateInfo)
{
    ui->setupUi(this);

    ui->certInfoFrame->setVisible(false);
    if (type == "theweb") {
        ui->summary->setText("This page is generated by theWeb.");
    } else if (type == "secure") {
        ui->summary->setText("This site is secure.");
    } else if (type == "unsecure") {
        ui->summary->setText("This site has no special security. Anyone can read what you send this website.");
    } else if (type == "ev") {
        ui->summary->setText("This site uses an extended validation certificate.");
    } else {
        ui->summary->setText("Missing description: " + type);
    }
}

CertificateInfo::~CertificateInfo()
{
    delete ui;
}

void CertificateInfo::on_pushButton_clicked()
{
    this->close();
}
